nginx-proxy:
  build: ./nginx-proxy/.
  container_name: nginx-proxy
  restart: always
  ports:
    # 80 should be open to the internet for letsencrypt purposes
    - "80:80"
    # 443 should be open to the internet for wss
    - "443:30334"
  volumes:
    - /home/core/ssl-certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
    DEFAULT_HOST: "kitsunet.metamask.io"

letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-nginx-proxy-companion
  restart: always
  volumes_from:
    - nginx-proxy
  volumes:
    - /home/core/ssl-certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro

ipfs-rendezvous-experiment:
  image: dryajov/ipfs-rendezvous-experiment
  restart: always
  ports:
    - "30333:30333"
    - "30334:30334"
  environment:
    - "ENV_ID=${ENV_ID}"
    VIRTUAL_PORT: "30334"
    VIRTUAL_HOST: "${ENV_ID}.kitsunet.metamask.io"
    LETSENCRYPT_HOST: "${ENV_ID}.kitsunet.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"

