webrtc-star-signaller:
  build: ./signaller/.
  container_name: webrtc-star
  restart: always
  ports:
    - "9090:9090"
  ulimits:
    nofile:
      soft: 20000
      hard: 40000
  environment:
    VIRTUAL_HOST: "signaller.kitsunet.metamask.io"
    VIRTUAL_PORT: "9090"
    LETSENCRYPT_HOST: "signaller.kitsunet.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"
