parity:
  image: parity/parity:v1.10.6
  container_name: parity
  restart: always
  ports:
    # 5001 will be used by the bridge
    # Should be closed in the machine,
    # and is mapped so we can perform local diagnostics with curl
    - "5001:5001"
    # 30303 is the RLPx port, should be open to the internet
    - "30303:30303"
    # JSON RPC Port
    - "8545:8545"
  volumes:
    - /home/core/parity-data:/parity-data
    - /home/core/peers:/parity-peers
    # Use this to log everything
    # -laccount_bloom,basicauthority,chain,client,dapps,discovery,diskmap,enact,engine,estimate_gas,ethash,executive,ext,external_tx,externalities,fatdb,fetch,hypervisor,ipc,jdb,journaldb,les,les_provider,local_store,migration,miner,mode,network,on_demand,own_tx,perf,poa,rcdb,shutdown,signer,snapshot,snapshot_io,snapshot_watcher,spec,state,stats,stratum,sync,trie,txqueue,updater=trace
  command: "--no-ancient-blocks --no-serve-light --max-peers 250 --snapshot-peers 50 --min-peers 50 --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 4096 --datadir /parity-data --cache 8192 --ipfs-api --ipfs-api-port 5001 --ipfs-api-hosts all --ipfs-api-interface 0.0.0.0 --jsonrpc-apis=all --jsonrpc-interface=0.0.0.0"
