parity:
  image: golang:1.10.3
  container_name: mustekala-geth
  restart: always
  ports:
    - "30304:30304"
  volumes:
    - /home/core/mustekala-geth:/go/src/github.com/metamask/go-ethereum
    - /home/core/geth-data/:/geth-data
  entrypoint: /go/src/github.com/metamask/go-ethereum/build/bin/geth
  command: "--fast --datadir /geth-data --maxpeers 250 --port 30304 --cache 4096"